### ISSUE TITLE
How can I use this package with svelte?

### ISSUE THREAD

**Issue by RicardoViteriR** [WebLogin/trendchart-elements#3]
Wondering if anyone has experience on how I could import this library using svelte.

the `tc-` tags don't work with the import statement neither the hover tooltip

```svelte
<script lang="ts">
  import '@weblogin/trendchart-elements';

</script>

<tc-column
	class="h-full w-full p-4 pt-0 [--shape-color:oklch(var(--pc))]"
	values="[12,10,12,4,13,16,14,10,12,11,17,18,16,17,20,14,15,13,12,14]"
	min="0"
	shape-radius="4"
	shape-gap="4"
></tc-column>
```

Here is a repl to demo the issue:
https://svelte.dev/repl/d56f19987687410dba37ef055124c6e4?version=4.2.0

Thanks!

**Comment by Mushr0000m** [comment]
Hi,

I'm not a Svelte user but I've done some research on your code and it looks the issue comes from your way of writting the `values` attribute. Svelte transform it to a simple string. By adding curly braces it interpolate it as an array : 
`values="{[12,10,12,4,13,16,14,10,12,11,17,18,16,17,20,14,15,13,12,14]}"` 

working example here : https://svelte.dev/repl/77e7b37671d9497a89b78d065f55e964?version=4.2.0

**Comment by RicardoViteriR** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
